### ISSUE TITLE
Edge cases fix

### ISSUE THREAD

**Issue by ivopaunov** [AmbireTech/wallet-login-sdk#11]
@cmihaylov 

Fix issue with SDK/EmailLogin component: hitting an edge case with infinite loading.

Merge main branch's latest changes to EmailLogin and AddAccount components, resolve conflicts and refactor.

**Comment by cmihaylov** [comment]
Fix issue with SDK/EmailLogin component: hitting an edge case with infinite loading.

Merge main branch's latest changes to EmailLogin and AddAccount components, resolve conflicts and refactor.
